### ISSUE TITLE
Use without root permissions?

### ISSUE THREAD

**Issue by insanity54** [fivdi/gpio-button#3]
Is there a way to run this without needing sudo?

**Comment by fivdi** [comment]
Apologies for not answering sooner. Typically it shouldn't need sudo. For example, user pi on Raspbian doesn't need sudo to use `gpio-button`. What have you tried and what were the issues related to sudo?

**Comment by fivdi** [comment]
@insanity54 I'm going to assume that nothing needs to be changed in gpio-button here. If it turns out that there is a problem with gpio-button the issue can be reopened.
